BUILD_TOP   := $(shell pwd)
DEVICE_PATH := device/samsung/gta4xlwifi

# BOARD

TARGET_BOARD_PLATFORM        := universal9611
TARGET_SLSI_VARIANT          := bsp
TARGET_SOC                   := exynos9611
TARGET_BOOTLOADER_BOARD_NAME := exynos9611
TARGET_BOARD_PLATFORM_GPU    := mali-g72
PRODUCT_PLATFORM             := exynos9611
TARGET_OTA_ASSER_DEVICE      := gta4xlwifi,gta4xlwifixx

TARGET_NO_BOOTLOADER := true

# CPU

TARGET_ARCH             := arm64
TARGET_ARCH_VARIANT     := armv8-a
TARGET_CPU_ABI          := arm64-v8a
TARGET_CPU_ABI2         :=
TARGET_CPU_VARIANT      := cortex-a53
TARGET_CPU_SMP          := true

TARGET_2ND_ARCH         := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI      := armeabi-v7a
TARGET_2ND_CPU_ABI2     := armeabi
TARGET_2ND_CPU_VARIANT  := cortex-a53

TARGET_SUPPORTS_64_BIT_APPS := true

# KERNEL

TARGET_PREBUILT_KERNEL       := $(DEVICE_PATH)/blobs/kernel
BOARD_PREBUILT_DTBIMAGE_DIR  := $(DEVICE_PATH)/blobs/dtbs
BOARD_INCLUDE_DTB_IN_BOOTIMG := true

BOARD_KERNEL_BASE            := 0x10000000
BOARD_KERNEL_OFFSET          := 0x00008000
BOARD_KERNEL_PAGESIZE        := 2048
BOARD_KERNEL_IMAGE_NAME      := Image

BOARD_DTB_OFFSET             := 0x00000000
BOARD_KERNEL_RAMDISK_OFFSET  := 0x01000000
BOARD_KERNEL_TAGS_OFFSET     := 0x00000100

# BOOT IMAGE

BOARD_BOOT_HEADER_VERSION    := 2
BOARD_BOOT_HEADER_NAME       := SRPSL20A007RU

BOARD_MKBOOTIMG_ARGS := --dtb_offset $(BOARD_DTB_OFFSET)
BOARD_MKBOOTIMG_ARGS += --kernel_offset $(BOARD_KERNEL_OFFSET)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_KERNEL_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --board $(BOARD_BOOT_HEADER_NAME)

# PARTITIONS

BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE  := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE  := ext4
BOARD_ODMIMAGE_FILE_SYSTEM_TYPE     := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE   := ext4

TARGET_COPY_OUT_VENDOR  := vendor
TARGET_COPY_OUT_ODM     := odm
TARGET_COPY_OUT_PRODUCT := product

AB_OTA_UPDATER := false

BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

BOARD_FLASH_BLOCK_SIZE             := 4096

BOARD_SUPER_PARTITION_SIZE         := 6585057280
BOARD_BOOTIMAGE_PARTITION_SIZE     := 61865984
BOARD_CACHEIMAGE_PARTITION_SIZE    := 209715200
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 71106560
BOARD_DTBOIMG_PARTITION_SIZE       := 8388608

BOARD_SUPER_PARTITION_GROUPS                    := samsung_dynamic_partitions
BOARD_SAMSUNG_DYNAMIC_PARTITIONS_SIZE           := 6580862976
BOARD_SAMSUNG_DYNAMIC_PARTITIONS_PARTITION_LIST := system vendor product odm

# RECOVERY

BOARD_HAS_DOWNLOAD_MODE      := true
TARGET_RECOVERY_PIXEL_FORMAT := "ABGR_8888"
TARGET_RECOVERY_FSTAB        := $(DEVICE_PATH)/recovery/root/system/etc/recovery.fstab

# TWRP

TW_INCLUDE_CRYPTO           := false
TW_NO_REBOOT_BOOTLOADER     := true
TW_HAS_DOWNLOAD_MODE        := true
RECOVERY_SDCARD_ON_DATA     := true
TW_NO_LEGACY_PROPS          := true
TW_NO_HAPTICS               := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
